server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      server:
        webmvc:
          routes:
            - id: tarot-route
              uri: lb://tarot-service
              predicates:
                - Path=/api/**
              metadata:
                response-timeout: 300000
    loadbalancer:
      cache:
        ttl: 10s
