spring.application.name=payment-service
server.port=8083
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.namespace=dev
dubbo.scan.base-packages=cc.usong.payment
dubbo.protocol.name=tri
dubbo.protocol.port=20883
dubbo.registry.address=nacos://localhost:8848
