spring.application.name=community-service
server.port=8085
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.namespace=dev
dubbo.scan.base-packages=cc.usong.community
dubbo.protocol.name=tri
dubbo.protocol.port=20885
dubbo.registry.address=nacos://localhost:8848
