spring.application.name=user-service
server.port=8082
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.namespace=dev
dubbo.scan.base-packages=cc.usong.user
dubbo.protocol.name=tri
dubbo.protocol.port=20882
dubbo.registry.address=nacos://localhost:8848
