spring.application.name=fortune-service
server.port=8084
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.namespace=dev
dubbo.scan.base-packages=cc.usong.fortune
dubbo.protocol.name=tri
dubbo.protocol.port=20884
dubbo.registry.address=nacos://localhost:8848
